#library "MRPGSkills"
#include "zcommon.acs"

Script "ConstSkillActivator" (void)
{
	if (CheckInventory("SKManaRegen") >= 1)
	{
		Giveinventory("Mana",1 * CheckInventory("SKManaRegen"));
	}
	
	if (CheckInventory("SKHealthRegen") >= 1)
	{
		if(CheckInventory("Health") < (20 * CheckInventory("SKHealthRegen")))
		{
			Giveinventory("Skillhealthgiver",1);
		}
	}
	Delay(35);
	Restart;
}

Script "SkillActivator" (void)
{
	Terminate;
}